In [1]:
!pip install rake_nltk
import pandas as pd
from rake_nltk import Rake
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import sigmoid_kernel

Requirement already satisfied: rake_nltk in /Users/omar/opt/anaconda3/lib/python3.8/site-packages (1.0.4)
Requirement already satisfied: nltk in /Users/omar/opt/anaconda3/lib/python3.8/site-packages (from rake_nltk) (3.5)
Requirement already satisfied: tqdm in /Users/omar/opt/anaconda3/lib/python3.8/site-packages (from nltk->rake_nltk) (4.47.0)
Requirement already satisfied: regex in /Users/omar/opt/anaconda3/lib/python3.8/site-packages (from nltk->rake_nltk) (2020.6.8)
Requirement already satisfied: joblib in /Users/omar/opt/anaconda3/lib/python3.8/site-packages (from nltk->rake_nltk) (0.16.0)
Requirement already satisfied: click in /Users/omar/opt/anaconda3/lib/python3.8/site-packages (from nltk->rake_nltk) (7.1.2)

In [2]:
df = pd.read_csv('datasetsfullplatform.csv', error_bad_lines=False, warn_bad_lines=False, low_memory=False)
df.head(10)
list(df)

['dataset_id',
 'title',
 'summary',
 'archive_note',
 'begin_date',
 'end_date',
 'spatial_type',
 'gcmd_science_keyword_id',
 'category',
 'topic',
 'term',
 'variable_level_1',
 'name']

In [3]:
df.head()

,dataset_id,title,summary,archive_note,begin_date,end_date,spatial_type,gcmd_science_keyword_id,category,topic,term,variable_level_1,name
0,5193,IBP Barrow Topographic Grid Point Data [Webber],<p>This dataset contains International Biologi...,NaN,9.471960e+10,1.009868e+12,raster,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,Field Survey
1,5366,"Geo-database of MNT, MAT, and Shrub Sites in N...",<p>This dataset contains the location and site...,NaN,9.545724e+11,9.715032e+11,raster,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,LANDSAT
2,6850,Glacial Geology Map of the Toolik Lake and Upp...,<p>This data set consists of a digital glacial...,NaN,1.051769e+12,1.051855e+12,NaN,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,Digital Elevation Model - DEM
3,8602,Barrow Area Information Database (BAID) Geospa...,<p>The Barrow Area Information Database (BAID)...,NaN,-6.942852e+11,1.265008e+12,point,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,"Satellite, RADARSAT"
4,8602,Barrow Area Information Database (BAID) Geospa...,<p>The Barrow Area Information Database (BAID)...,NaN,-6.942852e+11,1.265008e+12,point,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,LANDSAT

In [12]:
df['Key_words'] = ""

for index, row in df.iterrows():
    summary = row['summary']
    
    r = Rake()
    summary = str(summary)
    r.extract_keywords_from_text(summary)
    key_words_dict_scores = r.get_word_degrees()
    row['Key_words'] = list(key_words_dict_scores)
    
df.head()

,dataset_id,title,summary,archive_note,begin_date,end_date,spatial_type,gcmd_science_keyword_id,category,topic,term,variable_level_1,name,Key_words
0,5193,IBP Barrow Topographic Grid Point Data [Webber],<p>This dataset contains International Biologi...,NaN,9.471960e+10,1.009868e+12,raster,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,Field Survey,
1,5366,"Geo-database of MNT, MAT, and Shrub Sites in N...",<p>This dataset contains the location and site...,NaN,9.545724e+11,9.715032e+11,raster,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,LANDSAT,
2,6850,Glacial Geology Map of the Toolik Lake and Upp...,<p>This data set consists of a digital glacial...,NaN,1.051769e+12,1.051855e+12,NaN,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,Digital Elevation Model - DEM,
3,8602,Barrow Area Information Database (BAID) Geospa...,<p>The Barrow Area Information Database (BAID)...,NaN,-6.942852e+11,1.265008e+12,point,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,"Satellite, RADARSAT",
4,8602,Barrow Area Information Database (BAID) Geospa...,<p>The Barrow Area Information Database (BAID)...,NaN,-6.942852e+11,1.265008e+12,point,5,EARTH SCIENCE SERVICES,DATA ANALYSIS AND VISUALIZATION,GEOGRAPHIC INFORMATION SYSTEMS,NaN,LANDSAT,